#!/bin/bash

set -xeuo pipefail
BRANCH_TAG=$(echo "${BUILDKITE_BRANCH}" \
	  | tr '[:upper:]' '[:lower:]' \
      | sed -r 's/[_.\/]+/-/g');
REVISION_TAG=$(git rev-parse --short HEAD);
export BRANCH_TAG
export REVISION_TAG
